import 'mermaid_generator.dart';
import 'models.dart';
import 'config_reader.dart';

class HtmlGenerator {
  final FdgConfig? config;

  HtmlGenerator({this.config});

  String generate(Graph graph, {String title = 'Dependency Graph'}) {
    final mermaidGenerator = MermaidGenerator(config: config);
    final mermaidCode = mermaidGenerator.generate(graph);

    return '''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$title</title>
  <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #f5f5f5;
      min-height: 100vh;
      padding: 20px;
    }
    .container {
      max-width: 1400px;
      margin: 0 auto;
    }
    header {
      background: #fff;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      margin-bottom: 20px;
    }
    h1 { color: #333; font-size: 24px; }
    .stats {
      color: #666;
      font-size: 14px;
      margin-top: 8px;
    }
    .graph-container {
      background: #fff;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      overflow-x: auto;
    }
    .mermaid {
      display: flex;
      justify-content: center;
    }
    footer {
      text-align: center;
      color: #999;
      font-size: 12px;
      margin-top: 20px;
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>$title</h1>
      <div class="stats">${graph.nodes.length} files, ${graph.edges.length} dependencies</div>
    </header>
    <div class="graph-container">
      <pre class="mermaid">
$mermaidCode
      </pre>
    </div>
    <footer>
      Generated by fdg (flutter_dev_graph)
    </footer>
  </div>
  <script>
    mermaid.initialize({
      startOnLoad: true,
      theme: 'default',
      flowchart: {
        useMaxWidth: true,
        htmlLabels: true,
        curve: 'basis'
      }
    });
  </script>
</body>
</html>
''';
  }
}
